# Generated by Django 5.2.6 on 2025-09-12 07:57

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('auction_start_date', models.DateTimeField(db_index=True)),
                ('auction_end_date', models.DateTimeField(db_index=True)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('active_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('price_currency', models.CharField(choices=[('Dollars', 'Dollars'), ('Pounds', 'Pounds'), ('Naira', 'Naira'), ('Euro', 'Euro')], default='Dollars', max_length=10)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auction_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Item',
                'verbose_name_plural': 'Auction Items',
            },
            managers=[
                ('available_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ongoing', models.BooleanField(db_index=True, default=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_for_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.auctionitem')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_auctions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='auction_images/')),
                ('size', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auction_item_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('available_images', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='images',
            field=models.ManyToManyField(to='auction.auctionitemimage'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_bids', to='auction.auction')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('available_bids', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['item_name'], name='auction_auc_item_na_f471d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-created_at', 'amount'], name='auction_bid_auction_475389_idx'),
        ),
    ]
